### ISSUE TITLE
Update Pinax Quick Start and pinax/pinax README with new pinax-cli way of starting projects

### ISSUE THREAD

**Issue by ossanna16** [pinax/pinax#102]
Right now the [Quick Start](http://pinaxproject.com/pinax/quick_start/) in the [Pinax documentation](http://pinaxproject.com/pinax/) and the [README of this repository](https://github.com/pinax/pinax/blob/master/README.md) still show the "manual" way of starting Pinax starter projects. Since there's now an easier way to do that with the Pinax Command Line ([pinax-cli](https://github.com/pinax/pinax-cli)) both of these documents need to be updated. We'd like to give someone who has never contributed to open source before a chance to tackle this task in order to make their first OSS contribution. If you have contributed to open source before, please let someone else take this one. Below you can find some guidelines and instructions on what you need to do:

* Read [this blog post](http://blog.pinaxproject.com/2015/11/10/guide-how-contribute-pinax/) (especially the "how to make a pull request section") to learn what you need to to do set everything up. 
* Watch [this video](https://www.youtube.com/watch?v=l4yVb9zrbuw#action=share) and read [this blog post](http://blog.pinaxproject.com/2015/11/02/recap-october-pinax-hangout/) to learn how @brosner uses `pinax-cli` to install `pinax-project-blog`.
* Open the forked `pinax/pinax` repository in your text editor and update the "Getting Started" section in the `README.md` file with the new `pinax-cli` way of starting projects. Don't forget to save your changes. Please note that we use [Markdown syntax](https://daringfireball.net/projects/markdown/) for our documentation.
* In your text editor open the `docs` folder of the `pinax/pinax` repository and create a new file (right click "New File") named `quick_start_manual.md`.
* Open the `quick_start.md` file, copy the content, and paste it into your new `quick_start_manual.md` file. At the very top of the file you should change the title "Quick Start" to "Quick Start Manual", then save the file.
* Go back to the `quick_start.md` file and update the file the same way you updated the `README.md` file earlier to showcase the new `pinax-cli` way of starting projects.
* We want people to know that there is also a "manual way" of starting a project, not only the `pinax-cli` way so you should add one sentence to the document letting people know that if they are interested in learning about the manual way of installing a Pinax project, they should visit the "Quick Start Manual" page of the documentation. It would be good if you would link to this page from the `quick_start.md` page. Don't forget to save your changes.
* Since you created a new file, you need to add this file to the navigation bar of the documentation. To do that, open the file named `mkdocs.yml` and add the following line   `- ["quick_start_manual.md", "Introduction", "Quick Start Manual"]` right underneath this line `- ["quick_start.md", "Introduction", "Quick Start"]`. Save your changes.
* You also need to add the new file to the table of contents in the documentation. To do that open the `index.md` file and add the following line `* [Quick Start Manaual](quick_start_manual.md)` right underneath the following line `* [Quick Start](quick_start.md)`. Don't forget to save your changes.
* Let's see what our changes look like. To do so type `mkdocs serve` into your terminal. Make sure you `cd'd` into the folder in which you copied your forked repository first. Then type `127.0.0.1:8000/` into your browser and you should see the Pinax documentation including the changes you made. Awesome!
* Press the ctrl+c keys in order to stop the server, then follow the instructions ("how to make a pull request" section) [here](http://blog.pinaxproject.com/2015/11/10/guide-how-contribute-pinax/) to learn how to push your changes to your forked repository on GitHub and make a pull request.
* Celebrate! You are now an open source contributor! 🎉

One of us will then review your pull request and if everything looks great we will merge it (you will receive an email notification from GitHub). If you need to make additional changes, we will comment on your pull request and help you figure out the next steps. Don't worry, this is totally normal and doesn't mean that your pull request isn't awesome. Sometimes it just happens that a few things need to be tweaked. 

If you have any questions or need help, comment on this issue and mention me @ossanna16 (I will receive a notification this way). One of us will then reply and help you. It's even better if you would join our [Pinax Slack channel](http://slack.pinaxproject.com) (it's free). Someone is always there to help and answer any questions. If you'd like to reach me personally mention me @anna in our Pinax project Slack channel. Please remember that there are no stupid questions. We want to help you succeed and want to help you make your first open source contribution. 😊

**Comment by Charlotteis** [comment]
Hi! I'm the creator of twitter.com/yourfirstpr, a project that shares great starter issues with beginners to programming and open source. I just wanted to take the time to say wow, what an amazing and comprehensive issue! I think it the best I have seen so far and it makes me so happy.

I'll be tweeting this tomorrow afternoon (1PM GMT!).

Thank you again :sparkles: :sparkling_heart:

**Comment by ossanna16** [comment]
@Charlotteis Thank you for your kind words, Charlotte 😊 Could you please hold off until Friday evening? I scheduled some tweets about this from our Pinax project Twitter account which will go live around 5.45pm EST on Friday. Thank you! We're definitely planning on creating more issues like this one 😊

**Comment by Charlotteis** [comment]
Unfortunately that will be 22.45PM which is far too late (no-one in the UK will see it) so I'll have to do it the Saturday morning.

**Comment by ossanna16** [comment]
Sorry, I meant CET (I live in Germany), not EST so that should be 4.45pm UK time. If that's too late Saturday morning or sometime next week would work as well. Thanks again 😊

**Comment by Charlotteis** [comment]
A little bit too late for the schedule (I usually do things at 1PM). But I will see what I can do, if not, I'll do it on Monday :) Thanks again!

**Comment by ossanna16** [comment]
Awesome, thank you 👍

**Comment by ethankent** [comment]
Hi there!

I'm brand new when it comes to making OSS contributions. This looks like a great way to get started. Thanks for posting it. I'm in the process of trying it out.

Looks like the part of the issue dealing with README.md has already been addressed in a previous commit (364f8b04d004801c92c059bda4c056353575cfc7) I'm assuming it's ok to continue on with the other portions of the issue though.

Also, I noticed that in docs/quick_start.md the startproject command uses an argument "-n webpack.config.js" whereas the corresponding line in README.md did not. I'm assuming this not an issue and the argument can simply be left off in the cli version of the command.

Thanks again for posting this. I'm looking forward to sending a pull request!

**Comment by paltman** [comment]
@ethankent thanks!  yes, other parts are still relevant I think.  One thing to note is that `-n webpack.config.js` is no longer needed.

**Comment by ethankent** [comment]
Thanks @paltman! Hopefully everything looks good in my pull request.

**Comment by ethankent** [comment]
Hi there! I think this issue is close-able. If you need anything else, please let me know :)

**Comment by ossanna16** [comment]
Thanks @ethankent!
