### ISSUE TITLE
Describe how a new user can install a new application

### ISSUE THREAD

**Issue by ossanna16** [pinax/pinax#103]
So far the [Quick Start section](http://pinaxproject.com/pinax/quick_start/) in our Pinax documentation only shows how you can create a new project based on [pinax-project-account](https://github.com/pinax/pinax-project-account). Pinax projects are just Django projects and Pinax apps are just Django apps so you can add any Django app or any Pinax app to a Pinax starter project. We think it would be nice to show our users how to add one or two Pinax apps to their project after they got `pinax-project-account` up and running with the help of our Quick Start.
We'd like to give someone who has never contributed to open source before a chance to tackle this task in order to make their first OSS contribution. If you have contributed to open source before, please let someone else take this one. Below you can find some guidelines and instructions on what you need to do:

* Read [this blog post](http://blog.pinaxproject.com/2015/11/10/guide-how-contribute-pinax/) (especially the "how to make a pull request section") to learn what you need to to do set everything up.
* Watch [this video](https://www.youtube.com/watch?v=VEO9sh-anCQ) and read [this blog post](http://blog.pinaxproject.com/2015/11/25/recap-november-pinax-hangout/) (especially the "adding apps to starter projects" section) to learn more about `pinax-project-account` (what apps it consists of etc.) and how you can add apps to a Pinax project (or really any Django project).
* Open the forked `pinax/pinax` repository in your text editor, then open the `docs` folder, and finally open the `quick_start.md` file.
* At the very bottom of the file you should see this "TODO: Then add one more app". You can remove this line and add your description on how to add an app to a Pinax starter project. Don't forget to save your changes. Please note that we use [Markdown syntax](https://daringfireball.net/projects/markdown/) for our documentation.
* Let's see what our changes look like. To do so type `mkdocs serve` into your terminal. Make sure you `cd'd` into the folder in which you copied your forked repository first. Then type `127.0.0.1:8000/` into your browser and you should see the Pinax documentation including the changes you made. Awesome!
* Press the ctrl+c keys in order to stop the server, then follow the instructions ("how to make a pull request" section) [here](http://blog.pinaxproject.com/2015/11/10/guide-how-contribute-pinax/) to learn how to push your changes to your forked repository on GitHub and make a pull request.
* Celebrate! You are now an open source contributor! 🎉

One of us will then review your pull request and if everything looks great we will merge it (you will receive an email notification from GitHub). If you need to make additional changes, we will comment on your pull request and help you figure out the next steps. Don't worry, this is totally normal and doesn't mean that your pull request isn't awesome. Sometimes it just happens that a few things need to be tweaked. 

If you have any questions or need help, comment on this issue and mention me @ossanna16 (I will receive a notification this way). One of us will then reply and help you. It's even better if you would join our [Pinax Slack channel](http://slack.pinaxproject.com) (it's free). Someone is always there to help and answer any questions. If you'd like to reach me personally mention me @anna in our Pinax project Slack channel. Please remember that there are no stupid questions. We want to help you succeed and want to help you make your first open source contribution. 😊

**Comment by souravsingh** [comment]
Is the issue open? If so, I can make a quick PR for this

**Comment by ossanna16** [comment]
Hey @souravsingh , if you look in the top left corner it says "Open" so yes the issue is still open :) I would however ask you to only tackle this issue if you have never made an Open Source contribution before as this issue is intended for people wanting to make their first OSS contribution and therefore labelled `first-timers-only`.

**Comment by souravsingh** [comment]
I thought someone had made a PR for this issue before, Hence the question.As for OSS contribution, I do contribute to Scientific Python packages and wanted to try a easy issue in Django.

**Comment by ossanna16** [comment]
@souravsingh We haven't received a PR for this issue. As this is more of a Django documentation and not a Django code issue and you have contributed to OSS before, how about we try finding another Django issue for you that you can work on? I can't think of something off the top of my head, but would you mind joining our Pinax Slack team under this link http://slack.pinaxproject.com? I'm sure me and my team can think of something to work on for you and we'd love to chat with you in Slack. Thank you so much for your interest in Pinax and for contributing to OSS, you are awesome! :)

**Comment by shoshseiden** [comment]
@ossanna16 I'm just letting you know that I completed this issue yesterday. This was my first open source contribution, so feel free to contact me for any concerns since I am new to this.

**Comment by ossanna16** [comment]
@shoshseiden Thank you so much! This is awesome 🎉 Did you make a pull request? I don't see one yet. If you need help, please feel free to ping me here or in Slack. Signing off for the weekend but I'll be around on Monday to help or answer questions.

**Comment by shoshseiden** [comment]
@ossanna16 My pleasure! I just made the pull request. Thank you.

**Comment by ossanna16** [comment]
@shoshseiden Thanks so much! I'll take a look on Monday. Have a great weekend! :)
