### ISSUE TITLE
Checklist for 16.04 candidate apps

### ISSUE THREAD

**Issue by grahamu** [pinax/pinax#113]
**Update URLs to use namespaces**

Five changes must be made.
1. Change the URL names themselves, removing "pinax" or the application name (i.e. "announcements") and using a `<model>_<action>` name pattern.
2. Update the urlname references to include the namespace. These are typically found used by `reverse()`, `redirect()`, and `{% url ... %}`.
3. Update the project documentation to reference the namespace.
4. Update associated Pinax Starter Projects `project_name/urls.py` to use the namespace.
5. Update the project `tests/urls.py` to include the namespace:

Here is an example of messages/urls.py:

```
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^thread/(?P<pk>\d+)/delete/$", views.ThreadDeleteView.as_view(),
        name="thread_delete"),
    ...
]
```

New URL reference example:

```
reverse("pinax_messages:thread_delete", pk=thread_id)
```

Project tests/urls.py example:

```
from django.conf.urls import include, url


urlpatterns = [
    url(r"^", include("pinax.messages.urls", namespace="pinax_messages")),
]
```

**Update views from function-based to Django generic Class-Based-Views (CBV)**

In some cases this requires updating form inheritance to use `forms.ModelForm`.

**Make generic CBV-based class names consistent**

Let's make our Pinax view class names consistent across apps using the following convention:

```
class <model name><action>View():
```

For example, use `class AnnouncementCreateView()`. Do not use `CreateAnnouncement` or `AnnouncementCreate`.

**Explicitly specify view templates**

If a view uses Django's generic class-based views and requires a template, specify the template explicitly because Django's template loader will use an incorrect path.

For instance, pinax-messages needs a "thread_confirm_delete.html" template. If you do not specify the template path in `views.ThreadDeleteView()`, the template loader attempts to find `pinax_messages/thread_confirm_delete.html` by default. This does not work; the path you should explicitly use is `pinax/messages/thread_confirm_delete.html`.

**Update testing and Travis CI configuration**

Both `.travis.yml` and `tox.ini` should only include Django versions 1.8, 1.9, and master.

**Relocate templates**

Move template files out of app "templates" directory to [`pinax-theme-bootstrap`](https://github.com/pinax/pinax-theme-bootstrap).

**Rename templatetags file(s)**

Templatetag files should follow the naming convention, `pinax_<appname>_tags.py`. For instance, `pinax_testimonials_tags.py`.

**Create initial migration**

Create an initial migration if the application has concrete models and no "migrations" directory with `0001_initial.py`.

**Comment by KatherineMichel** [comment]
In the interest of narrowing down remaining issues, I'm adding this issue to a wiki page of important release links and closing issue. https://github.com/pinax/pinax/wiki/Historical-Release-Links
