### ISSUE TITLE
app.css and site.js   (Not Found)

### ISSUE THREAD

**Issue by xzmir** [pinax/pinax#138]
GET http://192.168.1.21:8002/site_media/static/css/app.css 404 (Not Found)
GET http://192.168.1.21:8002/site_media/static/js/site.js 404 (Not Found)

**Comment by KatherineMichel** [comment]
@xzmir Hello, try the guidance is in this PR and see if it works. It looks like you need to run the npm command, which prepares the static files. https://github.com/pinax/pinax/blob/adding-npm-guidance/docs/quick_start.md#modern-local-development-steps

**Comment by KatherineMichel** [comment]
@xzmir The guidance has now been merged into the main docs in quick start section. http://pinaxproject.com/pinax/quick_start/

**Comment by cjshaw1976** [comment]
@KatherineMichel There is no guidance on the quick_start. I am trying to get pinax to work and having never used sass, this has become a issue that will put me off with out some documentation.

**Comment by KatherineMichel** [comment]
@cjshaw1976 Hi Chris, Sass is actually a third-party framework that has been integrated into Pinax. Sass has its own full documentation. Here is the link to the docs. https://sass-lang.com/
Btw, the front-end process has recently been changed to use Webpack. You can find some guidance in the starter project branch READMEs. https://github.com/pinax/pinax-starter-projects/tree/account#-project_name-

**Comment by cjshaw1976** [comment]
Thank you for you explanation. The link you sent to a starter project does use webpack as you mentioned, but I installed **pinax-cli** and then used `pinax start blog mysite` to start a project. Here, webpack has not been implemented, but the sass files are there.

**Comment by KatherineMichel** [comment]
I forgot that Pinax Starter Projects are releases. Ok, that makes sense. Good to know. Before Webpack, an npm script was used.
