### ISSUE TITLE
Pinax Team Email Not Working

### ISSUE THREAD

**Issue by KatherineMichel** [pinax/pinax#139]
Per goodbetterbest user in Slack, the team@pinaxprojects.com email listed in app setup.py files is not working.

**Comment by jtauber** [comment]
Yeah, the domain name is wrong. Should be @pinaxproject.com

**Comment by KatherineMichel** [comment]
Closing issue, because has been noted in upcoming release planning doc: https://github.com/pinax/pinax/wiki/Pinax-19.xx-Proposed-Process
