### ISSUE TITLE
Standardize AUTHORS Files and Automate Adding Authors

### ISSUE THREAD

**Issue by KatherineMichel** [pinax/pinax#148]
Authors files could be standardized. More than one format is used. Also, consider adding a script to automate addition of authors to the file. See pip repo as an example: https://github.com/pypa/pip/blob/master/tasks/generate.py

**Comment by mfonism** [comment]
Hello @KatherineMichel 

I made an attempt at a utility for listing the authors in a repo.

https://gist.github.com/mfonism/29c03f780175612eb8efde899e15a246

```py
import subprocess
from collections import OrderedDict


def get_git_repo_authors(path_to_repo):
    """
    Returns a generator object of the authors in a git repo.
    """
    cmd = ["git", "-C", path_to_repo, "log", "--reverse", "--format=format:%aN <%aE>"]
    resp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

    authors = OrderedDict()
    # why not a list?
    # because that would be grossly inefficient for sufficiently large data
    # why not a set?
    # because we need to preserve insertion order

    for line in map(
        lambda line_bytes: line_bytes.decode().strip(), resp.stdout.readlines()
    ):
        if line not in authors:
            authors[line] = ""
    return (a for a in authors)


if __name__ == "__main__":
    # plug-in the path to a git repo on your device
    # the one below exists on a Lenovo Thinkpad X240 in Nigeria 😸 
    # and that's probably the only place it exists in the world!
    repo_path = r"C:/Users/Mfonism/Codeville/OSSDjango/Pinax/pinax-likes"
    for author in get_git_repo_authors(repo_path):
        print(author)
```

And here's a screenshot of the output when printed to console for a test repo.

![git_authors](https://user-images.githubusercontent.com/50708034/68526287-0811e680-02d2-11ea-8147-6c413a79c831.png)

This brings up a few questions:

__How do we treat duplicate entries for the same author?__
As is the case with __Jeff Bowen__ whos has two entries accounting for their two different email addresses, and with __kthrnmichel@gmail.com__ who has two entries accounting for their two different usernames.
* IDEA: Use mailmap
    * CRITIQUE: That has to be managed manually, which is what we're trying to solve in the first place!

__How do we order the authors?__
For now, they're ordered FIFO-style with respect to their first contributions.
* IDEA: Alphabetical ordering might be easier on the eyes.

What's your take on this?

I'd really love to work on this.

**Comment by mfonism** [comment]
An hour away from my computer, and I realize the list of authors could be fetched with __git shortlog__ in such a way that one no longer needs to remove duplicate author entries with Python (as is done in the _for_ loop in the code above).

```
git shortlog -se
```

This emits a shortlog summarized by author, providing a count of each author's commits, and showing the email of each author.

This way, we just need to strip out the count info (can be done in the subprocess call) and the interspersed newline characters.

**Comment by KatherineMichel** [comment]
@mfonism Thank you for this. Going to make a note of it in the WIP release plan notes.

**Comment by KatherineMichel** [comment]
Closing issue because it's now documented in our Pinax 20.XX and 20.08 Release Plans: https://github.com/pinax/pinax/wiki
