### ISSUE TITLE
dist.pinaxproject.com does not offer TLS

### ISSUE THREAD

**Issue by alex** [pinax/pinax#65]
This causes pip to warn about it, and exposes users to potential MITM attacks. It would be good to offer TLS, and ideally require it.

**Comment by meshy** [comment]
Or better yet, the packages could just be uploaded to PyPI.

**Comment by jtauber** [comment]
If there are any packages still in use that rely on dist.pinaxproject.com rather than PyPI, please let us know. We'd like to get rid of dist.pinaxproject.com all together if possible.

**Comment by meshy** [comment]
I'd rather use PyPI, but I am still reliant for `dist.pinaxproject.com` in order to download a number of requirements for a legacy app (the upgrade process is ongoing, but slow moving).

**Comment by jtauber** [comment]
@meshy what in particular do you need?

**Comment by meshy** [comment]
Here's the relevant snippet from the requirements file. 

```
--index-url=http://dist.pinaxproject.com/dev/

diff-match-patch==20090804
django-atomformat==0.1.1.dev1
django-email-confirmation==0.2.dev2
django-groups==0.1.dev11
django-mailer==0.2a1.dev3
django-microblogging==0.2.dev1
django-timezones==0.2.dev1
ybrowserauth==1.2
http://dist.pinaxproject.com/dev/Pinax/Pinax-0.9a1.tar.gz
```

They're pretty out of date, I realise. `</embarrassment>`

The last one is a direct link because the index recently stopped working for that particular item.

**Comment by KatherineMichel** [comment]
Closing issue. I don't believe it is relevant any longer. If I'm wrong, feel free to re-open.
