### ISSUE TITLE
create pinax-project-waitlinglist

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax#72]
- pinax-project-waitlinglist ?
  - django-waitinglist
  - pinax-referrals (modify to link to non-users?)

**Comment by brosner** [comment]
django-waitinglist has been moved to pinax-waitinglist. The new starter project branch has been pushed. No pinax-referrals at this point.

**Comment by ossanna16** [comment]
Can this issue be closed since a starter project has been created? Maybe we could open a new one for pinax-referrals?

**Comment by KatherineMichel** [comment]
pinax-waiting-list exists and has its own issue in that repo. Closing issue. https://github.com/pinax/pinax-starter-projects/issues/13
