### ISSUE TITLE
Start Hosting Monthly Pinax Hangouts

### ISSUE THREAD

**Issue by paltman** [pinax/pinax#78]
We should leverage Google Hangouts to host a monthly time to take 30-60 minutes and cover some aspect of Pinax with a live audience that can interrupt and ask questions and contribute to the conversation.

We should record these so we can post them on the Pinax blog.

I propose the 3rd Thursday of every month at Noon US/Central time, for lack of a better recurring calendar time.

@ossanna16 had mentioned using Google Hangout on Air and https://tlk.io for help chat.

**Comment by paltman** [comment]
@ossanna16 had mentioned to me privately that it might be a good idea to defer starting this until later in the fall when the Pinax core contributors might be less busy, especially with DjangoCon consuming 1/4 of September.

**Comment by paltman** [comment]
You make a good point @ossanna16, but i think we can still pull it off. I don't want them to be too scripted anyway. I view them more as a chance to get some folks together for a short bit and have some fun. I also fully expect the first several to be learning experiences and I kind of rather get them out of the way so we can get into a groove.

**Comment by jtauber** [comment]
I'd rather start off sooner with just less content than later with more prep.

**Comment by ossanna16** [comment]
Does August 20th sound good for the first Hangout? We just need to decide on a time. I can promote the event via Twitter. I would suggest using Google Hangout on Air (also lets you record and upload to Youtube afterwards as far as I know) and either http://tlk.io or our Pinax Slack channel for people to ask questions. Do we want people to sign up via Eventbrite so we know how many to expect?

**Comment by jtauber** [comment]
I think we can mark this done!
