### ISSUE TITLE
Write "How to Contribute" section for the docs

### ISSUE THREAD

**Issue by paltman** [pinax/pinax#79]

**Comment by ossanna16** [comment]
I started writing this "How to contribute" guide targeted at beginners https://docs.google.com/document/d/1f9hPTw3nelWy7nxaDawWP7EUl4QyeGeC4BNYeb4iWhU/edit
Feedback and suggestions are more than welcome :)
I thought we could either add it to the Pinax docs or publish it as a blog post.

**Comment by KatherineMichel** [comment]
Closing because this appears to have been completed.
