### ISSUE TITLE
Fix issue with out of the box experience, webpack command not being available in starter projects

### ISSUE THREAD

**Issue by paltman** [pinax/pinax#82]
`webpack` docs say to do both, `npm install webpack -g` and have it in your `package.json` for local install referencing as a lib.

**Comment by jtauber** [comment]
what's the issue, though?

**Comment by KatherineMichel** [comment]
I'm thinking this issue should be closed. Installing webpack globally is not a best practice (see link below), and pinax-starter-projects now use django-webpack-loader. https://webpack.js.org/guides/installation/#global-installation
