### ISSUE TITLE
Proposal: pinax command line

### ISSUE THREAD

**Issue by paltman** [pinax/pinax#88]
#### Purpose

Having a `pinax` command line utility will help users more easily get started with Pinax starter projects, allow for better discovery, and enable us to provide a richer bootstrapping experience.

##### projects start

There could very well be many commands, but initially, we'll focus on just a single command and that is starting a project:

```
pip install pinax
pinax projects start account
```

or:

```
pip install pinax
pinax projects start
```

Then you get a list of available projects with a short one line description and the ability to pick one.

###### Project Registry

The project registry should be JSON or YAML hosted either in the `pinax/pinax` repo or the `pinax/pinax-starter-projects` repo and start initially with the following format:

```json
{
    "zero": {
        "url": "https://github.com/pinax/pinax-starter-projects/zipball/zero",
        "args": "-n webpack.config.js",
    },
    "account": {
        "url": "https://github.com/pinax/pinax-starter-projects/zipball/account",
        "args": "-n webpack.config.js",
    },
}
```

We can eventually add more things like a `requirements` dict to each project, other variables to setup, etc. that extend the Django project template feature.

**Comment by paltman** [comment]
Consider http://click.pocoo.org/5/ for building the command line client

**Comment by paltman** [comment]
You can install via `pip` from within Python by using it's API:

```python
from pip.commands import install
command = install.InstallCommand()
opts, args = command.parser.parse_args()
command.run(opts, ["requests"])
```

**Comment by jtauber** [comment]
could we also just do it with an `install_requires` in `setup.py`?

**Comment by paltman** [comment]
You can start the project from Python too. No need to shell out:

```python
from pip.commands import install
command = install.InstallCommand()
opts, args = command.parser.parse_args()
command.run(opts, ["Django"])

from django.core.management import call_command
call_command("startproject", NAME, "-n webpack.config.js", template="https://github.com/pinax/pinax-starter-projects/zipball/account")
```

**Comment by paltman** [comment]
@jtauber I like the idea of each starter project specifying it's Django version and this command just installing what the registry tells it to.

**Comment by jtauber** [comment]
ah, nice idea

**Comment by jtauber** [comment]
will the registry be a JSON/YAML file under this repo?

**Comment by paltman** [comment]
I was at first thinking in `pinax-starter-projects`, but I think it like it living in `pinax/pinax` better

**Comment by paltman** [comment]
But maybe it's something that should be versioned and deployed somewhere. Not sure.

**Comment by paltman** [comment]
For now, as long as we can read a `.json|yml` file from a url, that's all i care about

**Comment by jtauber** [comment]
Well, it being a JSON/YAML file in a GitHub repo, it is kinda versioned and deployed :-)

**Comment by paltman** [comment]
:+1:

**Comment by paltman** [comment]
You can now:

```pip install pinax-cli```

Repo: http://github.com/pinax/pinax-cli
