### ISSUE TITLE
Describe how a new user can install more than one application

### ISSUE THREAD

**Issue by mroswell** [pinax/pinax#90]
For instance, if you wanted to add a Wiki to the Account starter project.

**Comment by jtauber** [comment]
This is covered in http://blog.pinaxproject.com/2015/11/25/recap-november-pinax-hangout/ specifically in the section **Adding Apps to Starter Projects**. Perhaps we could adapt that for the docs /cc @ossanna16

**Comment by ossanna16** [comment]
@jtauber Sorry, I just saw this now. Yes, we should definitely adapt it for the documentation. Instead of doing it myself I'll close this issue and create another first-timers-only issue, if that's okay with you. I think this would be a great issue to tackle for someone who is new to open source 😊

**Comment by jtauber** [comment]
@ossanna16 :+1:

**Comment by ossanna16** [comment]
Turned this into another first-timers-only issue https://github.com/pinax/pinax/issues/103 so closing this one.
