### ISSUE TITLE
Document Expectations for Each Pinax App / Starter Project / Theme

### ISSUE THREAD

**Issue by paltman** [pinax/pinax#98]

**Comment by KatherineMichel** [comment]
I swear I've seen this somewhere. Can't think of where. Does anyone know?

**Comment by KatherineMichel** [comment]
In the interest of narrowing down remaining issues, I'm adding this issue to a wiki page of important release links and closing issue. https://github.com/pinax/pinax/wiki/Historical-Release-Links
